name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build release binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: cem
            asset_name: cem-linux-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: cem
            asset_name: cem-macos-aarch64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install Just
      uses: extractions/setup-just@v2

    # Use just to build (consistent with development)
    - name: Build release binary
      run: just build

    - name: Strip binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: strip target/release/${{ matrix.artifact_name }}

    - name: Create tarball
      run: |
        cd target/release
        tar czf ../../${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
        cd ../..

    - name: Upload binary to release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.asset_name }}.tar.gz
